#spring.application.name=cloud-native-config-service
spring:
  application:
    name: cloud-native-config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/asanobm/cloud-native-config-service.git
          default-label: main